version: 2.1

# Orbs are shareable packages of CircleCI configuration you can use to simplify your builds.
orbs:
  # The Heroku orb is used to simplify the deployment to Heroku
  heroku: circleci/heroku@1.2.6

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build

jobs:
  # This job builds the application.
  build:
    docker:
      - image: node:current-alpine
    steps:
      # Checkout the git repository
      - checkout
      - run:
          name: build
          # The yarn build command is configured in the package.json under scripts
          command: |
            yarn
            yarn build
      - store_artifacts:
          path: build/index.js
      - persist_to_workspace:
          root: .
          paths:
            - .

  #... build job from previous step...

  # Our pipeline is responsible for testing our software.
  # If one or more tests fail, the deployment shouldn't get executed.
  test:
    docker:
      - image: node:current-alpine
    parallelism: 1
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          # The test command is configured in the package.json.
          command: |
            yarn
            yarn test
